services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ts_fastify_api
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && node dist/index.js"
volumes:
  pgdata:
